"""Generated data-only size debt manifest. Regenerate with scripts/regenerate_size_ratchet.py."""

BASELINE_SOURCE_SHA = "77d6827b7a72a632899bb6cc64a7e759aabcfaa6"

GIANT_PATHS = (
    "devtools/benchmarks/osworld/run_cu_bridge_agent.py",
    "devtools/benchmarks/osworld/run_step_agent.py",
    "ouroboros/extension_loader.py",
    "ouroboros/llm.py",
    "ouroboros/loop.py",
    "ouroboros/review_state.py",
    "ouroboros/tools/claude_advisory_review.py",
    "ouroboros/tools/control.py",
    "ouroboros/tools/core.py",
    "ouroboros/tools/git.py",
    "ouroboros/tools/registry.py",
    "server.py",
    "skills/unix_computer_use/plugin.py",
    "supervisor/events.py",
    "supervisor/git_ops.py",
    "supervisor/workers.py",
    "tests/test_agent_task_pipeline.py",
    "tests/test_cancel_intents_phase_a.py",
    "tests/test_claudexor_owned_daemon.py",
    "tests/test_context.py",
    "tests/test_delegated_subagent_transport.py",
    "tests/test_delivery_forced_finalization.py",
    "tests/test_devtools_benchmarks.py",
    "tests/test_evolution_state_integrity_v3.py",
    "tests/test_extension_loader.py",
    "tests/test_extensions_api.py",
    "tests/test_git_ops_recovery.py",
    "tests/test_git_review_pipeline.py",
    "tests/test_headless_cli.py",
    "tests/test_loop_misc.py",
    "tests/test_model_slot_role_model.py",
    "tests/test_osworld_cu_bridge.py",
    "tests/test_preflight_runner.py",
    "tests/test_promote_chat_flow.py",
    "tests/test_review_agent_session_route.py",
    "tests/test_review_substrate_v2.py",
    "tests/test_runtime_mode_core.py",
    "tests/test_runtime_mode_elevation.py",
    "tests/test_scope_review.py",
    "tests/test_skill_exec.py",
    "tests/test_skill_loader.py",
    "tests/test_skill_review.py",
    "tests/test_task_status_flow.py",
    "tests/test_tool_capabilities.py",
    "tests/test_ui_smoke_playwright.py",
    "tests/test_workspace_executor.py",
    "web/modules/chat.js",
    "web/tests/harness_accounts.test.js",
)

FUNCTION_DEBT = (
    ("ouroboros/agent_startup_checks.py", "verify_restart"),
    ("supervisor/events.py", "_handle_schedule_task"),
)

BAND_BASELINE_PATHS = (
    "devtools/benchmarks/swe_bench_pro/e1v2/run_pro.py",
    "devtools/benchmarks/terminal_bench/harbor_installed_agent.py",
    "devtools/benchmarks/terminal_bench/run_tb.py",
    "launcher.py",
    "ouroboros/agent_startup_checks.py",
    "ouroboros/claudexor_runtime.py",
    "ouroboros/context.py",
    "ouroboros/extension_process_runner.py",
    "ouroboros/gateway/contracts.py",
    "ouroboros/gateway/extensions.py",
    "ouroboros/gateway/history.py",
    "ouroboros/gateway/tasks.py",
    "ouroboros/launcher_bootstrap.py",
    "ouroboros/loop_llm_call.py",
    "ouroboros/loop_tool_execution.py",
    "ouroboros/outcomes.py",
    "ouroboros/platform_layer.py",
    "ouroboros/preflight_runner.py",
    "ouroboros/protected_artifacts.py",
    "ouroboros/skill_loader.py",
    "ouroboros/skill_review_runner.py",
    "ouroboros/subagents.py",
    "ouroboros/task_results.py",
    "ouroboros/task_status.py",
    "ouroboros/tools/browser.py",
    "ouroboros/tools/shell_guards.py",
    "ouroboros/tools/skill_exec.py",
    "ouroboros/utils.py",
    "ouroboros/workspace_executor.py",
    "scripts/run_external_review.py",
    "skills/telegram/plugin.py",
    "skills/telegram/scripts/companion.py",
    "skills/telegram/scripts/sidecar.py",
    "supervisor/evolution_lifecycle.py",
    "supervisor/terminal_delivery.py",
    "tests/test_acting_subagents.py",
    "tests/test_advisory_observability.py",
    "tests/test_build_scripts.py",
    "tests/test_claude_code_gateway.py",
    "tests/test_commit_gate.py",
    "tests/test_contracts.py",
    "tests/test_evolution_redesign.py",
    "tests/test_observability_outcomes_v2.py",
    "tests/test_onboarding_complete_endpoint.py",
    "tests/test_onboarding_wizard.py",
    "tests/test_packaged_runtime_and_lifecycle.py",
    "tests/test_review_fidelity.py",
    "tests/test_review_verification_v6544.py",
    "tests/test_safety_policy.py",
    "tests/test_swe_pro_e1v2.py",
    "tests/test_telegram_miniapp_lifecycle.py",
    "tests/test_tool_api_v2_public_surface.py",
    "tests/test_usage_accounting.py",
    "tests/test_v647_megacommit.py",
    "tests/test_v6730_origin_invariant.py",
    "tests/test_v678_receipt_reconciliation.py",
    "web/modules/harness_accounts.js",
    "web/modules/harness_login_cards.js",
    "web/modules/log_events.js",
    "web/modules/onboarding_wizard.js",
    "web/modules/settings.js",
    "web/modules/widgets.js",
)

BAND_PATHS = {
    "devtools/benchmarks/cybergym/cybergym_adapter.py": "Stateful campaign layer after the protocol split (ratchet heal); shrink next touch.",
    "devtools/benchmarks/cybergym/cybergym_docker.py": "Docker runtime layer of the executor split: one container-machinery seam.",
    "devtools/benchmarks/cybergym/cybergym_executor.py": "Executor assembly after docker/lifecycle/wire splits (ratchet heal); shrink next touch.",
    "devtools/benchmarks/cybergym/cybergym_lifecycle.py": "Run/settle lifecycle layer of the executor split: one accounting seam.",
    "devtools/benchmarks/cybergym/cybergym_protocol.py": "Stateless protocol layer of the adapter split: constants, validators, provenance.",
    "devtools/benchmarks/cybergym/cybergym_sidecar.py": "Sidecar attestation core after the observations split (ratchet heal); shrink next touch.",
    "devtools/benchmarks/cybergym/run_cybergym.py": "CyberGym launcher is one submit-shaped entry point (drift heal); split when a second arm lands.",
    "devtools/benchmarks/swe_bench_pro/e1v2/run_pro.py": None,
    "devtools/benchmarks/terminal_bench/harbor_installed_agent.py": None,
    "devtools/benchmarks/terminal_bench/run_tb.py": None,
    "ouroboros/agent.py": "Subagent message identity now lives in a shared helper; keep agent.py below the giant-file threshold rather than re-expanding it.",
    "ouroboros/agent_startup_checks.py": "Shrank below 1500 by moving the envelope producer to the contracts SSOT; band re-entry is the reduction's artifact.",
    "ouroboros/artifacts.py": "Exact task-source persistence and repository-diff materialization now share the actor-readable artifact seam for acceptance evidence.",
    "ouroboros/cancel_intents.py": "Entered the band from 929 lines: reciprocal timeout-retry lineage validation and physical-leaf/logical-root aliasing stay with the durable cancel-intent mutation authority so Stop-now hardens the same request across retry races.",
    "ouroboros/capability_evidence.py": "Grew INTO the band by the #284 fix: a fresh exact-model density witness may honestly undercut the cold floor \u2014 evidence logic belongs beside the witness store it reads.",
    "ouroboros/consciousness.py": "Durable Background Consciousness observation inbox and bounded truthful replay",
    "ouroboros/extension_process_runner.py": None,
    "ouroboros/gateway/control.py": "Entered the band from 966 lines: the update-flow redesign added the shared stash-first prologue (_stash_local_work_fenced/_unwind_stashed_update) and the review-wave affordability floor to the update apply orchestration (update-flow-redesign sprint, Q9/Q10 owner decisions).",
    "ouroboros/gateway/history.py": None,
    "ouroboros/gateway/settings.py": "Retiring persistent auto-Low removed the former giant debt; the remaining owner and reviewer settings endpoints stay centralized while tracked in the shrinking band.",
    "ouroboros/loop_tool_execution.py": None,
    "ouroboros/marketplace/ouroboroshub.py": "Entered the band from 373 lines: the hubflow sprint added the adopt transaction (eligibility prelude, CAS re-verification, move-aside + state-quintet snapshot, verified rollback with per-step error collection, retention finalize) beside the existing install/update flows (hubflow sprint, adopt-in-ouroboroshub owner decision D4).",
    "ouroboros/observability.py": "Entered the band from 820 lines: child task copy-back now promotes only promised observability CAS manifests/blobs and task-owned source handles into canonical storage before headless GC, with typed unavailable gaps and retry metadata.",
    "ouroboros/platform_layer.py": "Shrank INTO the band: the retired Claude-SDK runtime probes (resolve_claude_runtime, ClaudeRuntimeState) were deleted with the transport (owner-approved Q4 retirement); no new content was added.",
    "ouroboros/preflight_runner.py": None,
    "ouroboros/projects_registry.py": "Entered the band from 999 lines: the stuck-Working liveness sprint homed the project-thread membership lens (mtime-cached) and its broadcast-choke marker here \u2014 registry semantics belong to the registry, not to message_bus.",
    "ouroboros/protected_artifacts.py": None,
    "ouroboros/review.py": "Entered the band from 952 lines: re-anchoring the size ratchet on the official line added the candidate and pairwise base-vs-tip transition validators (validate_size_ratchet_candidate/validate_size_ratchet_transition_against_base) with merge-aware previous-manifest resolution, replacing the retired first-parent history audit (update-flow-redesign sprint, Q7-C/Q18-A/Q19-A owner decisions).",
    "ouroboros/review_custody.py": "Review custody now owns the shared typed retry-rail history and frozen actor reconstruction so physical outcomes cannot be lost between the substrate and reconciliation.",
    "ouroboros/review_execution.py": "Verdict extraction and the native tool-round executor moved to their own modules (generic reviewer-actor sprint); the transport seam re-enters the band smaller and more cohesive.",
    "ouroboros/reviewer_slot_config.py": "Absorbed the reviewer_slots() builder from review_substrate (altitude) and configured-subagent row resolution for the generic reviewer-actor bridge.",
    "ouroboros/safety.py": "Entered the band from 954 lines with the safety-supervisor rate-limit fix: ONE shared model-call helper now serves both the primary and repair safety calls (it already deletes the duplicated call block), recognising a provider rate limit in BOTH wire shapes, taking one bounded deadline-capped backoff plus one retry, then blocking that one call with the typed non-verdict SAFETY_UNAVAILABLE outcome plus a durable audit row (a short storm latch answers further checks in the window without provider calls); the bounded newest-first conversation budget is the second half.",
    "ouroboros/skill_review_runner.py": None,
    "ouroboros/subagent_runtime.py": "Configured-retry refusals mirrored typed (triad 2026-08-30) push the module just over 1000; no new subsystem, same seam.",
    "ouroboros/task_results.py": "Authority reads need an explicit strict mode so malformed child records cannot become a false zero count.",
    "ouroboros/task_status.py": None,
    "ouroboros/tools/browser.py": None,
    "ouroboros/tools/commit_gate.py": "Grew INTO the band by the review-wave fix binding the actor reference (delivery class) into the commit review contract fingerprint \u2014 same-module contract identity, splitting it would separate the fingerprint from its gate.",
    "ouroboros/tools/plan_review_runtime.py": "Entered the band from 986 lines: timeout custody synthesis joined the existing plan-review runtime owner while preserving profile-continuity disclosures and typed health facts during target integration.",
    "ouroboros/tools/review_context_atlas.py": "Grew INTO the band by the #284 pack-arithmetic fixes: measured render charged at admission, exact per-row costs, target capped at the hard rail, honest eviction diagnostics \u2014 all in the module that owns the arithmetic.",
    "ouroboros/tools/skill_exec.py": None,
    "ouroboros/tools/skill_publish.py": "Entered the band from 952 lines: publish now writes the OuroborosHub publication receipt at pr_opened through the shared locked-update seam and maps the receipt from the validated serialized form (hubflow sprint, receipt-as-only-stored-fact design).",
    "ouroboros/utils.py": None,
    "ouroboros/workspace_executor.py": None,
    "scripts/run_external_review.py": None,
    "skills/telegram/plugin.py": None,
    "skills/telegram/scripts/companion.py": None,
    "skills/telegram/scripts/sidecar.py": None,
    "supervisor/evolution_lifecycle.py": None,
    "supervisor/message_bus.py": "push_log gained the A2A frame suppression and explicit-addressing contract comments in the live log routing fix (fix/main-chat-leak sprint); the module sat at exactly 1000 lines before it",
    "supervisor/task_reaper.py": "Entered the band from 907 lines: timeout-retry admission now serializes queue publication, reciprocal result lineage, cancellation-wins handoff, and failed-terminal-write custody in the existing off-loop reaper owner.",
    "supervisor/terminal_delivery.py": None,
    "tests/test_acting_subagents.py": None,
    "tests/test_advisory_observability.py": None,
    "tests/test_build_scripts.py": None,
    "tests/test_commit_gate.py": None,
    "tests/test_contracts.py": None,
    "tests/test_cybergym_protocol.py": "CyberGym protocol suite arrived in one piece with the benchmark (drift heal); split when the next protocol family lands.",
    "tests/test_delegated_skill_payload.py": "Sol scope-review fix batch: P1 trust probes (forged index, symlinked git metadata), P2 golden-E2E review close and schema/docs pins joined the existing R1+gate-fix payload suite.",
    "tests/test_evolution_redesign.py": None,
    "tests/test_external_workspace_access.py": "Deliverables custody matrix covers nested roots, executor aliases, Presence ceilings, and direct shell target semantics.",
    "tests/test_loop_transport_wait.py": "Contract suite for the transport-wait episode: classification, custody, round-level wait, terminals, and the final-review regression pins live together as one coherent surface.",
    "tests/test_managed_review_subject.py": "Lane L-review contract suite: the managed resolution-delta subject (gate/advisory surfaces, M0 fallback), Q25-A admission, Q28-A yield outcomes and enforcement-honest advisory texts grew past 1000 across the adversarial fix round; one subject, one suite.",
    "tests/test_nested_rights_depth.py": "Nested delegation depth authority regression coverage",
    "tests/test_observability_outcomes_v2.py": None,
    "tests/test_onboarding_complete_endpoint.py": None,
    "tests/test_onboarding_wizard.py": None,
    "tests/test_owner_stop_s3.py": "Entered the band from 821 lines: the S3 contract suite now covers retry-root aliasing, graceful-to-immediate hardening, stale-control drain races, hard deadline preservation, descendant settlement failure, and late resweep exactly-once root finalization.",
    "tests/test_packaged_runtime_and_lifecycle.py": None,
    "tests/test_provider_failure_reporting.py": "Entered the band from 938 lines: the provider-failure honesty rework added the retry-wall marker suites (entry-clear, all-retryable stamp, empty-response provider-failing gate, no-repay rail) beside the cost-validation suites (bool/NaN/inf/negative/huge-int at both boundaries) - one file per failure-reporting surface.",
    "tests/test_repo_health_smoke.py": "size-ratchet redesign: merge-aware previous, pairwise base-vs-tip, candidate-mode generator contract tests",
    "tests/test_review_cycles_dispatch.py": "Task acceptance wallet and paid-stamp dispatch regression matrix was integrated from the current managed target alongside the existing review-cycle tests.",
    "tests/test_review_fidelity.py": None,
    "tests/test_review_verification_v6544.py": None,
    "tests/test_reviewer_slot_config.py": "Existing suite grew by successor pins for the shared actor-row vocabulary (subagent_id round-trip, api_chat spelling); splitting the module would separate the contract from its historical pins.",
    "tests/test_safety_policy.py": None,
    "tests/test_skill_review_runner.py": "Skill lifecycle/review terminal-state regression coverage stays one focused suite below the 1500-line band cap.",
    "tests/test_swe_pro_e1v2.py": None,
    "tests/test_telegram_miniapp_lifecycle.py": None,
    "tests/test_terminal_durability_v664.py": "Entered the band from 974 lines: terminal durability coverage now pins retry-admission failure custody so an unpersisted terminal row cannot publish task_done or lose the retry marker.",
    "tests/test_timeout_policy.py": "Adaptive timeout and custody regression suite covers raw-deadline admission, explicit finalization reserve, transport bounds, and late-result reconciliation.",
    "tests/test_usage_accounting.py": None,
    "tests/test_v6730_origin_invariant.py": None,
    "tests/test_v678_receipt_reconciliation.py": None,
    "web/modules/api_types.js": "The shared browser contract module now includes issue 265 publication-preflight types alongside the target settings and subagent contracts.",
    "web/modules/harness_accounts.js": None,
    "web/modules/log_events.js": None,
    "web/modules/onboarding_wizard.js": "Shrank INTO the band: the Claude Runtime onboarding card and its /api/claude-code/* polling were deleted with the retired transport (owner-approved Q4); no new content was added.",
    "web/modules/review_presentation.js": "Review Checkpoint read-side grouping, lifecycle/verdict separation, and keyed disclosure reconciliation remain one pure adapter below the 1500-line band cap.",
    "web/modules/reviewer_slots.js": "Owner-approved 5A editor: per-row Direct model / Configured subagent source picker with read-only derived disclosure replaces the legacy Claude-SDK advisory input in the same module that owns reviewer-row editing.",
    "web/modules/settings.js": None,
    "web/modules/widgets.js": None,
    "web/tests/harness_login_cards.test.js": "Login-card suite grew past 1000 lines with the name-the-account face cases (agy pickup, issue #232); split when the next face lands.",
    "web/tests/review_presentation.test.js": "Review Checkpoint lifecycle and verdict reconciliation remain covered by one focused presentation suite.",
}

BYTE_BASELINE_DEBT = {
    "ouroboros/llm.py": 205432,
    "ouroboros/loop.py": 335600,
    "supervisor/events.py": 205328,
    "tests/test_delegated_subagent_transport.py": 320627,
    "tests/test_devtools_benchmarks.py": 328786,
    "web/modules/chat.js": 234467,
}

BYTE_DEBT = {
    "ouroboros/loop.py": 312707,
    "tests/test_delegated_subagent_transport.py": 320340,
    "tests/test_devtools_benchmarks.py": 328116,
    "web/modules/chat.js": 224244,
}
