"""Generated data-only size debt manifest. Regenerate with scripts/regenerate_size_ratchet.py."""

BASELINE_SOURCE_SHA = "77d6827b7a72a632899bb6cc64a7e759aabcfaa6"

GIANT_PATHS = (
    "devtools/benchmarks/osworld/run_cu_bridge_agent.py",
    "devtools/benchmarks/osworld/run_step_agent.py",
    "ouroboros/extension_loader.py",
    "ouroboros/llm.py",
    "ouroboros/loop.py",
    "ouroboros/review_state.py",
    "ouroboros/tools/claude_advisory_review.py",
    "ouroboros/tools/control.py",
    "ouroboros/tools/core.py",
    "ouroboros/tools/git.py",
    "ouroboros/tools/registry.py",
    "server.py",
    "skills/unix_computer_use/plugin.py",
    "supervisor/events.py",
    "supervisor/git_ops.py",
    "supervisor/workers.py",
    "tests/test_agent_task_pipeline.py",
    "tests/test_cancel_intents_phase_a.py",
    "tests/test_claudexor_owned_daemon.py",
    "tests/test_context.py",
    "tests/test_delegated_subagent_transport.py",
    "tests/test_delivery_forced_finalization.py",
    "tests/test_devtools_benchmarks.py",
    "tests/test_evolution_state_integrity_v3.py",
    "tests/test_extension_loader.py",
    "tests/test_extensions_api.py",
    "tests/test_git_ops_recovery.py",
    "tests/test_git_review_pipeline.py",
    "tests/test_headless_cli.py",
    "tests/test_loop_misc.py",
    "tests/test_model_slot_role_model.py",
    "tests/test_osworld_cu_bridge.py",
    "tests/test_plan_review.py",
    "tests/test_preflight_runner.py",
    "tests/test_promote_chat_flow.py",
    "tests/test_review_agent_session_route.py",
    "tests/test_review_prompt_caching.py",
    "tests/test_review_substrate_v2.py",
    "tests/test_runtime_mode_core.py",
    "tests/test_runtime_mode_elevation.py",
    "tests/test_scope_review.py",
    "tests/test_skill_exec.py",
    "tests/test_skill_loader.py",
    "tests/test_skill_review.py",
    "tests/test_task_status_flow.py",
    "tests/test_tool_capabilities.py",
    "tests/test_ui_smoke_playwright.py",
    "tests/test_workspace_executor.py",
    "web/modules/chat.js",
    "web/tests/harness_accounts.test.js",
)

FUNCTION_DEBT = (
    ("ouroboros/agent_startup_checks.py", "verify_restart"),
    ("supervisor/events.py", "_handle_schedule_task"),
)

BAND_BASELINE_PATHS = (
    "devtools/benchmarks/swe_bench_pro/e1v2/run_pro.py",
    "devtools/benchmarks/terminal_bench/harbor_installed_agent.py",
    "devtools/benchmarks/terminal_bench/run_tb.py",
    "launcher.py",
    "ouroboros/agent_startup_checks.py",
    "ouroboros/claudexor_runtime.py",
    "ouroboros/context.py",
    "ouroboros/extension_process_runner.py",
    "ouroboros/gateway/contracts.py",
    "ouroboros/gateway/extensions.py",
    "ouroboros/gateway/history.py",
    "ouroboros/gateway/tasks.py",
    "ouroboros/launcher_bootstrap.py",
    "ouroboros/loop_llm_call.py",
    "ouroboros/loop_tool_execution.py",
    "ouroboros/outcomes.py",
    "ouroboros/platform_layer.py",
    "ouroboros/preflight_runner.py",
    "ouroboros/protected_artifacts.py",
    "ouroboros/skill_loader.py",
    "ouroboros/skill_review_runner.py",
    "ouroboros/subagents.py",
    "ouroboros/task_results.py",
    "ouroboros/task_status.py",
    "ouroboros/tools/browser.py",
    "ouroboros/tools/shell_guards.py",
    "ouroboros/tools/skill_exec.py",
    "ouroboros/utils.py",
    "ouroboros/workspace_executor.py",
    "scripts/run_external_review.py",
    "skills/telegram/plugin.py",
    "skills/telegram/scripts/companion.py",
    "skills/telegram/scripts/sidecar.py",
    "supervisor/evolution_lifecycle.py",
    "supervisor/terminal_delivery.py",
    "tests/test_acting_subagents.py",
    "tests/test_advisory_observability.py",
    "tests/test_build_scripts.py",
    "tests/test_claude_code_gateway.py",
    "tests/test_commit_gate.py",
    "tests/test_contracts.py",
    "tests/test_evolution_redesign.py",
    "tests/test_observability_outcomes_v2.py",
    "tests/test_onboarding_complete_endpoint.py",
    "tests/test_onboarding_wizard.py",
    "tests/test_packaged_runtime_and_lifecycle.py",
    "tests/test_review_fidelity.py",
    "tests/test_review_verification_v6544.py",
    "tests/test_safety_policy.py",
    "tests/test_swe_pro_e1v2.py",
    "tests/test_telegram_miniapp_lifecycle.py",
    "tests/test_tool_api_v2_public_surface.py",
    "tests/test_usage_accounting.py",
    "tests/test_v647_megacommit.py",
    "tests/test_v6730_origin_invariant.py",
    "tests/test_v678_receipt_reconciliation.py",
    "web/modules/harness_accounts.js",
    "web/modules/harness_login_cards.js",
    "web/modules/log_events.js",
    "web/modules/onboarding_wizard.js",
    "web/modules/settings.js",
    "web/modules/widgets.js",
)

BAND_PATHS = {
    "devtools/benchmarks/swe_bench_pro/e1v2/run_pro.py": None,
    "devtools/benchmarks/terminal_bench/harbor_installed_agent.py": None,
    "devtools/benchmarks/terminal_bench/run_tb.py": None,
    "launcher.py": None,
    "ouroboros/agent.py": "the turn loop; shed 222 lines to ouroboros/executor_dispatch.py in this change",
    "ouroboros/agent_startup_checks.py": None,
    "ouroboros/claudexor_runtime.py": None,
    "ouroboros/context.py": None,
    "ouroboros/execd_spool.py": "RWS v2: the target's bounded result spool, one subject",
    "ouroboros/execd_state.py": "RWS v2: the target's durable custody, journal and lease state",
    "ouroboros/export_policy_contract.py": "the ONE export judge; splitting it would recreate the multi-door shape it exists to end",
    "ouroboros/extension_process_runner.py": None,
    "ouroboros/gateway/contracts.py": None,
    "ouroboros/gateway/extensions.py": None,
    "ouroboros/gateway/history.py": None,
    "ouroboros/gateway/tasks.py": None,
    "ouroboros/launcher_bootstrap.py": None,
    "ouroboros/loop_llm_call.py": None,
    "ouroboros/loop_tool_execution.py": None,
    "ouroboros/outcomes.py": None,
    "ouroboros/platform_layer.py": None,
    "ouroboros/preflight_runner.py": None,
    "ouroboros/projects_registry.py": "upstream registry plus the sealed remote placement field",
    "ouroboros/protected_artifacts.py": None,
    "ouroboros/remote_transfer.py": "RWS v2: the Home side of the import boundary, where returned manifests are validated",
    "ouroboros/remote_workspace.py": "RWS v2: the Home-side remote workspace service",
    "ouroboros/skill_loader.py": None,
    "ouroboros/skill_review_runner.py": None,
    "ouroboros/subagents.py": None,
    "ouroboros/task_results.py": None,
    "ouroboros/task_status.py": None,
    "ouroboros/tools/browser.py": None,
    "ouroboros/tools/shell_guards.py": None,
    "ouroboros/tools/skill_exec.py": None,
    "ouroboros/utils.py": None,
    "ouroboros/workspace_executor.py": None,
    "ouroboros/workspace_payload_native.py": "RWS v2: the target's payload staging and declared-output snapshots",
    "ouroboros/workspace_query_native.py": "RWS v2: the target's search and code-query operations",
    "scripts/run_external_review.py": None,
    "skills/telegram/plugin.py": None,
    "skills/telegram/scripts/companion.py": None,
    "skills/telegram/scripts/sidecar.py": None,
    "supervisor/evolution_lifecycle.py": None,
    "supervisor/terminal_delivery.py": None,
    "tests/test_acting_subagents.py": None,
    "tests/test_advisory_observability.py": None,
    "tests/test_build_scripts.py": None,
    "tests/test_claude_code_gateway.py": None,
    "tests/test_commit_gate.py": None,
    "tests/test_evolution_redesign.py": None,
    "tests/test_execd_spool.py": "coverage for the spool's quota and cancellation paths",
    "tests/test_observability_outcomes_v2.py": None,
    "tests/test_onboarding_complete_endpoint.py": None,
    "tests/test_onboarding_wizard.py": None,
    "tests/test_packaged_runtime_and_lifecycle.py": None,
    "tests/test_project_remote_placement.py": "coverage for placement rebinding, generation fencing and session close",
    "tests/test_review_fidelity.py": None,
    "tests/test_review_verification_v6544.py": None,
    "tests/test_safety_policy.py": None,
    "tests/test_swe_pro_e1v2.py": None,
    "tests/test_telegram_miniapp_lifecycle.py": None,
    "tests/test_tool_api_v2_public_surface.py": None,
    "tests/test_usage_accounting.py": None,
    "tests/test_v647_megacommit.py": None,
    "tests/test_v6730_origin_invariant.py": None,
    "tests/test_v678_receipt_reconciliation.py": None,
    "web/modules/harness_accounts.js": None,
    "web/modules/harness_login_cards.js": None,
    "web/modules/log_events.js": None,
    "web/modules/onboarding_wizard.js": None,
    "web/modules/settings.js": None,
    "web/modules/widgets.js": None,
}

BYTE_BASELINE_DEBT = {
    "ouroboros/llm.py": 205432,
    "ouroboros/loop.py": 335600,
    "supervisor/events.py": 205328,
    "tests/test_delegated_subagent_transport.py": 320627,
    "tests/test_devtools_benchmarks.py": 328786,
    "web/modules/chat.js": 234467,
}

BYTE_DEBT = {
    "ouroboros/llm.py": 205432,
    "ouroboros/loop.py": 335600,
    "supervisor/events.py": 205328,
    "tests/test_delegated_subagent_transport.py": 320627,
    "tests/test_devtools_benchmarks.py": 328786,
    "web/modules/chat.js": 234467,
}
