"""Generated data-only size debt manifest. Regenerate with scripts/regenerate_size_ratchet.py."""

BASELINE_SOURCE_SHA = "77d6827b7a72a632899bb6cc64a7e759aabcfaa6"

GIANT_PATHS = (
)

MODULE_DEBT_1500 = (
)

FUNCTION_DEBT = (
    ("ouroboros/agent_startup_checks.py", "verify_restart"),
    ("supervisor/events_schedule_task.py", "_handle_schedule_task"),
)

BAND_BASELINE_PATHS = (
    "devtools/benchmarks/swe_bench_pro/e1v2/run_pro.py",
    "devtools/benchmarks/terminal_bench/harbor_installed_agent.py",
    "devtools/benchmarks/terminal_bench/run_tb.py",
    "launcher.py",
    "ouroboros/agent_startup_checks.py",
    "ouroboros/claudexor_runtime.py",
    "ouroboros/context.py",
    "ouroboros/extension_process_runner.py",
    "ouroboros/gateway/contracts.py",
    "ouroboros/gateway/extensions.py",
    "ouroboros/gateway/history.py",
    "ouroboros/gateway/tasks.py",
    "ouroboros/launcher_bootstrap.py",
    "ouroboros/loop_llm_call.py",
    "ouroboros/loop_tool_execution.py",
    "ouroboros/outcomes.py",
    "ouroboros/platform_layer.py",
    "ouroboros/preflight_runner.py",
    "ouroboros/protected_artifacts.py",
    "ouroboros/skill_loader.py",
    "ouroboros/skill_review_runner.py",
    "ouroboros/subagents.py",
    "ouroboros/task_results.py",
    "ouroboros/task_status.py",
    "ouroboros/tools/browser.py",
    "ouroboros/tools/shell_guards.py",
    "ouroboros/tools/skill_exec.py",
    "ouroboros/utils.py",
    "ouroboros/workspace_executor.py",
    "scripts/run_external_review.py",
    "skills/telegram/plugin.py",
    "skills/telegram/scripts/companion.py",
    "skills/telegram/scripts/sidecar.py",
    "supervisor/evolution_lifecycle.py",
    "supervisor/terminal_delivery.py",
    "tests/test_acting_subagents.py",
    "tests/test_advisory_observability.py",
    "tests/test_build_scripts.py",
    "tests/test_claude_code_gateway.py",
    "tests/test_commit_gate.py",
    "tests/test_contracts.py",
    "tests/test_evolution_redesign.py",
    "tests/test_observability_outcomes_v2.py",
    "tests/test_onboarding_complete_endpoint.py",
    "tests/test_onboarding_wizard.py",
    "tests/test_packaged_runtime_and_lifecycle.py",
    "tests/test_review_fidelity.py",
    "tests/test_review_verification_v6544.py",
    "tests/test_safety_policy.py",
    "tests/test_swe_pro_e1v2.py",
    "tests/test_telegram_miniapp_lifecycle.py",
    "tests/test_tool_api_v2_public_surface.py",
    "tests/test_usage_accounting.py",
    "tests/test_v647_megacommit.py",
    "tests/test_v6730_origin_invariant.py",
    "tests/test_v678_receipt_reconciliation.py",
    "web/modules/harness_accounts.js",
    "web/modules/harness_login_cards.js",
    "web/modules/log_events.js",
    "web/modules/onboarding_wizard.js",
    "web/modules/settings.js",
    "web/modules/widgets.js",
)

BAND_PATHS = {
    "devtools/benchmarks/osworld/run_cu_bridge_agent.py": "OSWorld persistent-agent launcher: main(), the admission/finalization seams the launcher gate walks, and the single run/outcome path, after the prompt, tool-policy, gate and budget leaves were extracted verbatim",
    "devtools/benchmarks/swe_bench_pro/e1v2/run_pro.py": None,
    "devtools/benchmarks/terminal_bench/harbor_installed_agent.py": None,
    "devtools/benchmarks/terminal_bench/run_tb.py": None,
    "launcher.py": None,
    "ouroboros/agent.py": "per-worker agent orchestrator (Env, OuroborosAgent, make_agent) after the delegated-child dispatch seam was extracted into ouroboros/agent_dispatch.py behind the compatibility facade (v7 lane L-C2)",
    "ouroboros/agent_startup_checks.py": None,
    "ouroboros/agent_task_pipeline.py": "task pipeline after the L-C2 synthesis extraction; orchestration wiring, still shrinking with the campaign",
    "ouroboros/claudexor_runtime.py": None,
    "ouroboros/context.py": None,
    "ouroboros/delegate_custody.py": "durable custody row owner after the DEL1 reconciliation split: the event vocabulary, replay, settlement, cancellation and containment-fault writers stay with the rows they author while the sweeps live in delegate_custody_reconcile.py behind the compatibility facade",
    "ouroboros/extension_process_runner.py": None,
    "ouroboros/gateway/contracts.py": None,
    "ouroboros/gateway/extensions.py": None,
    "ouroboros/gateway/history.py": None,
    "ouroboros/gateway/settings.py": "Retiring persistent auto-Low removed the former giant debt; the remaining owner and reviewer settings endpoints stay centralized while tracked in the shrinking band.",
    "ouroboros/gateway/tasks.py": None,
    "ouroboros/launcher_bootstrap.py": None,
    "ouroboros/loop_llm_call.py": None,
    "ouroboros/loop_tool_execution.py": None,
    "ouroboros/mcp_client.py": "native MCP ToolResult producer with exact public string compatibility",
    "ouroboros/outcomes.py": None,
    "ouroboros/platform_layer.py": None,
    "ouroboros/preflight_runner.py": None,
    "ouroboros/protected_artifacts.py": None,
    "ouroboros/review.py": "v7 size-gate owner: blob-id-cached ref inventory keeps the exact per-commit history audit affordable (204s->21s) without sampling commits",
    "ouroboros/review_execution.py": "review execution rail after the L-C session-verdict extraction; route vocabulary and executor seam, still shrinking with the review-stack campaign",
    "ouroboros/skill_loader.py": None,
    "ouroboros/skill_review_runner.py": None,
    "ouroboros/subagent_worktrees.py": "private-snapshot registry owner: strict-vs-soft reads, the typed corruption refusal and the Git-branch cleanup symmetry keep the acting-worktree and delegated-snapshot lifecycles in the one module that holds their cross-process ops lock",
    "ouroboros/subagents.py": None,
    "ouroboros/task_status.py": None,
    "ouroboros/tools/browser.py": None,
    "ouroboros/tools/core.py": "retains the direct core tool catalog plus write, edit, text-search, and worker-forwarding implementations after semantic-no-op read/list and delivery extraction",
    "ouroboros/tools/delegate.py": "nanny verb owner after the DEL1 terminal-evidence split: the start/wait/cancel verbs, their guards and the tool catalog stay with the surface the model calls while the terminal story lives in delegate_terminal.py behind the compatibility facade",
    "ouroboros/tools/registry_core.py": "ToolRegistry execution authority extracted verbatim behind the compatibility facade while preserving guard and dispatch order",
    "ouroboros/tools/registry_guards.py": "consolidates existing root/CWD/workspace/git process receiver guards without semantic or ABI change",
    "ouroboros/tools/review.py": "review tool surface after the L-C multi-model extraction; facade wiring plus the review tool entrypoints, still shrinking with the review-stack campaign",
    "ouroboros/tools/shell_guards.py": None,
    "ouroboros/tools/skill_exec.py": None,
    "ouroboros/tools/subagent_integration.py": "subagent patch integration owner after the DEL1 disposition split: locate/verify/verdict plumbing, the external-workspace and coop verification lanes and integrate_subagent_patch stay together while the delegated-run disposition seam lives in subagent_integration_delegated.py behind the compatibility facade",
    "ouroboros/usage_accounting.py": "usage accounting after the L-C2 legacy-import extraction; accounting rails, still shrinking with the campaign",
    "ouroboros/utils.py": None,
    "ouroboros/workspace_executor.py": None,
    "scripts/run_external_review.py": None,
    "server.py": "composition root of the server host: it keeps the lifespan, the supervisor loop, the owner-command dispatch and the process state those three need (bound event loop, bound port, supervisor-generation handles, panic entry), which cannot move to a leaf without a back-edge",
    "skills/telegram/plugin.py": None,
    "skills/telegram/scripts/companion.py": None,
    "skills/telegram/scripts/sidecar.py": None,
    "skills/unix_computer_use/plugin.py": "local macOS/Linux computer-use substrate plus the register(api) entry point after the connection-registry, remote-backend and shared-runtime leaves were extracted verbatim",
    "supervisor/evolution_lifecycle.py": None,
    "supervisor/terminal_delivery.py": None,
    "supervisor/update_merge.py": "managed-update tx/lock/stash/rollback/boot-recovery primitives after the merge-planning and live-materialization cluster was extracted into supervisor/update_merge_plan.py behind the compatibility facade (v7 lane 1A)",
    "tests/test_acting_subagents.py": None,
    "tests/test_advisory_observability.py": None,
    "tests/test_build_scripts.py": None,
    "tests/test_claude_code_gateway.py": None,
    "tests/test_claudexor_owned_daemon.py": "upstream v6.105.0 added the rotation-reconcile lifecycle suite (13 tests plus the _ReconcileGateway/_rotation_receipt_path helpers) to the module that already owns the owned-daemon ensure/attach lifecycle; the four unified-accounts tests from the same upstream block were re-homed to their themed siblings, so what grew here is the parent's own theme",
    "tests/test_commit_gate.py": None,
    "tests/test_contracts.py": None,
    "tests/test_delegated_skill_payload.py": "Sol scope-review fix batch: P1 trust probes (forged index, symlinked git metadata), P2 golden-E2E review close and schema/docs pins joined the existing R1+gate-fix payload suite.",
    "tests/test_evolution_redesign.py": None,
    "tests/test_external_review_script.py": "v7 tool-owner trust-boundary coverage extends the upstream contributor-review regression suite",
    "tests/test_observability_outcomes_v2.py": None,
    "tests/test_onboarding_complete_endpoint.py": None,
    "tests/test_onboarding_wizard.py": None,
    "tests/test_packaged_runtime_and_lifecycle.py": None,
    "tests/test_plan_review_engine.py": "upstream v6.103.0 plan-review engine characterization suite arrives banded from the release itself; splitting a just-landed upstream suite inside the adoption merge would forfeit verbatim traceability to its source",
    "tests/test_repo_health_smoke.py": "v7 1500-line layer activation regression coverage",
    "tests/test_review_fidelity.py": None,
    "tests/test_review_verification_v6544.py": None,
    "tests/test_safety_policy.py": None,
    "tests/test_swe_pro_e1v2.py": None,
    "tests/test_telegram_miniapp_lifecycle.py": None,
    "tests/test_tool_api_v2_public_surface.py": None,
    "tests/test_tool_result.py": "typed tool-result characterization suite; two upstream tool_call_id trace fields crossed it into the band",
    "tests/test_usage_accounting.py": None,
    "tests/test_v647_megacommit.py": None,
    "tests/test_v6730_origin_invariant.py": None,
    "tests/test_v678_receipt_reconciliation.py": None,
    "tests/test_v7_migration_ledger.py": "the migration-ledger membership test grows one named block per extraction lane by design; the blocks are data (row inventories), and moving them out would recreate the very second-ledger the SSOT rule forbids",
    "web/modules/chat.js": "chat instance shell after the W3 wave D ownership transfers: mostly factory composition wiring plus the WS routing that binds the extracted owners; still shrinking with the chat.js size campaign",
    "web/modules/harness_accounts.js": None,
    "web/modules/harness_login_cards.js": None,
    "web/modules/log_events.js": None,
    "web/modules/onboarding_wizard.js": None,
    "web/modules/settings.js": None,
    "web/modules/widgets.js": None,
    "web/tests/harness_login_cards.test.js": "upstream v6.104.0 agy login-card suite arrives banded from the release itself; same adoption-merge traceability rule",
}

BYTE_BASELINE_DEBT = {
    "ouroboros/llm.py": 205432,
    "ouroboros/loop.py": 335600,
    "supervisor/events.py": 205328,
    "tests/test_delegated_subagent_transport.py": 320627,
    "tests/test_devtools_benchmarks.py": 328786,
    "web/modules/chat.js": 234467,
}

BYTE_DEBT = {
}
